#!/usr/bin/env bash

set -e

cd "$(dirname "${BASH_SOURCE[0]}")" && vagrant_dir=$PWD

source "${vagrant_dir}/scripts/functions.sh"
resetNestingLevel

# TODO: Add status messages
cd "${vagrant_dir}/scripts" && eval $(minikube docker-env) && docker build -t magento2-kubernetes:dev -f ./Dockerfile ../scripts
cd "${vagrant_dir}" && kubectl delete deployment magento2 && python local_deploy.py --all --ingress

info "$(regular)See details in $(bold)${vagrant_dir}/log/${current_script_name}.log$(regular). For debug output set $(bold)debug:vagrant_project$(regular) to $(bold)1$(regular) in $(bold)etc/config.yaml$(regular)"
