#!/usr/bin/env bash

vagrant_dir=$(cd "$(dirname "$0")"; pwd)

# Enable trace printing and exit on the first error
set -ex

arguments=$@
cd "${vagrant_dir}"
vagrant ssh -c "\$MAGENTO_ROOT/bin/magento $arguments"