#!/usr/bin/env bash

set -e

vagrant_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)

source "${vagrant_dir}/scripts/functions.sh"

cd "${vagrant_dir}"
vagrant ssh -c "bash /vagrant/scripts/guest/m-clear-cache" 2> >(logError)
