#!/usr/bin/env bash

set -e

cd "$(dirname "${BASH_SOURCE[0]}")" && vagrant_dir=$PWD

source "${vagrant_dir}/scripts/output_functions.sh"
resetNestingLevel

bash "${vagrant_dir}/scripts/host/m_composer.sh" "$@" 2> >(logError)

info "See detailed log in '${vagrant_dir}/log/debug.log'"
