#!/usr/bin/env bash

set -e

vagrant_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)

source "${vagrant_dir}/scripts/functions.sh"
resetNestingLevel

bash "${vagrant_dir}/scripts/host/m_reinstall.sh" "$@" 2> >(logError)
