#!/usr/bin/env bash

vagrant_dir=$(cd "$(dirname "$0")"; pwd)
magento_ce_dir="${vagrant_dir}/magento2ce"
magento_ce_sample_data_dir="${magento_ce_dir}/magento2ce-sample-data"
magento_ee_sample_data_dir="${magento_ce_dir}/magento2ee-sample-data"
php_executable=$(bash "${vagrant_dir}/scripts/host/get_path_to_php.sh")

# Enable trace printing and exit on the first error
set -ex

with_sample_data=0
while [ "$1" != "" ]; do
    case $1 in
        -s | --sample-data )    with_sample_data=1
                                ;;
        * )                     ;;
    esac
    shift
done

# As a precondition, disable CE sample data
if [ -f ${magento_ce_sample_data_dir}/dev/tools/build-sample-data.php ]; then
    ${php_executable} -f ${magento_ce_sample_data_dir}/dev/tools/build-sample-data.php -- --command=unlink --ce-source="${magento_ce_dir}" --sample-data-source="${magento_ce_sample_data_dir}"
    set +x
    echo "CE Sample data disabled"
    set -x
fi
# As a precondition, disable EE sample data
if [ -f ${magento_ee_sample_data_dir}/dev/tools/build-sample-data.php ]; then
    ${php_executable} -f ${magento_ee_sample_data_dir}/dev/tools/build-sample-data.php -- --command=unlink --ce-source="${magento_ce_dir}" --sample-data-source="${magento_ee_sample_data_dir}"
    set +x
    echo "EE Sample data disabled"
    set -x
fi

if [ ${with_sample_data} = 1 ]; then
    # Installing CE or EE, in both cases CE sample data should be linked
    if [ ! -f ${magento_ce_sample_data_dir}/dev/tools/build-sample-data.php ]; then
        # Sample data not available and should be enabled
        set +x
        echo "CE Sample data repository is not available. Recreate project using \"init_project.sh -fc\", which will delete Magento code base and recreate project from scratch. Or clone sample data to <project_dir>/magento2ce/magento2ce-sample-data."
        set -x
        exit 0
    else
        # Sample data available and should be enabled
        set +x
        echo "CE Sample data enabled"
        set -x
        ${php_executable} -f ${magento_ce_sample_data_dir}/dev/tools/build-sample-data.php -- --command=link --ce-source="${magento_ce_dir}" --sample-data-source="${magento_ce_sample_data_dir}"
    fi

    if [ -f ${magento_ce_dir}/app/etc/aliases_to_classes_map.json ]; then
        # Installing EE
        if [ ! -f ${magento_ee_sample_data_dir}/dev/tools/build-sample-data.php ]; then
            # Sample data not available and should be enabled
            set +x
            echo "EE Sample data repository is not available. Recreate project using \"init_project.sh -fc\", which will delete Magento code base and recreate project from scratch. Or clone sample data to <project_dir>/magento2ce/magento2ee-sample-data."
            set -x
            exit 0
        else
            # Sample data available and should be enabled
            set +x
            echo "EE Sample data enabled"
            set -x
            ${php_executable} -f ${magento_ee_sample_data_dir}/dev/tools/build-sample-data.php -- --command=link --ce-source="${magento_ce_dir}" --sample-data-source="${magento_ee_sample_data_dir}"
        fi
    fi
fi

cd ${vagrant_dir}
vagrant ssh -c "m-reinstall"