#!/usr/bin/env bash

vagrant_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)

source "${vagrant_dir}/scripts/functions.sh"

cd "${vagrant_dir}"
vagrant ssh -c "/vagrant/scripts/guest/m-search-engine ${@}" 2> >(logError) > >(log)
