#!/usr/bin/env bash

set -ex

# Get args
while getopts 'fh:c:' flag; do
  case "${flag}" in
    h) help=1 ;;
    c) command=$OPTARG ;;
    f) force_restart_services=1 ;;
    *) help=1 ;;
  esac
done

if [ $help ]; then
    echo "Usage: ./m-varnish -c enable/disable (-f to force restart services)"
    exit 0
fi

# Check if user created config.yaml file
if [ ! -f ./etc/config.yaml ]; then
    echo "Please make sure you have create a config.yaml file copy from etc/config.yaml.dist"
    exit 0
fi

if [[ $command == "enable" ]]; then
    sed -ie "s/use_varnish:.*/use_varnish: 1/" ./etc/config.yaml
elif [[ $command == "disable" ]]; then
    sed -ie "s/use_varnish:.*/use_varnish: 0/" ./etc/config.yaml
else
    echo "Usage: ./m-varnish -c enable/disable (-f to force restart services)"
    exit 0
fi

vagrant_dir=$(cd "$(dirname "$0")"; pwd)
cd ${vagrant_dir}
if [[ $force_restart_services == 1 ]]; then
    vagrant ssh -c "sudo bash /vagrant/scripts/guest/configure_varnish -f"
else
    vagrant ssh -c "sudo bash /vagrant/scripts/guest/configure_varnish"
fi
