#!/usr/bin/env bash
# See unlink_configs script

# Enable trace printing and exit on the first error
set -ex

# Make guest configs visible and editable in the host IDE

# Configs located under /etc/*
configs=( apache2 php mysql varnish rabbitmq crontab cron.d timezone hosts profile profile.d )
for config in "${configs[@]}"
do
    if [ ! -d /vagrant/etc/guest/${config} ] && [ ! -f /vagrant/etc/guest/${config} ]; then
        if [ -d /etc/${config} ] || [ -f /etc/${config} ]; then
            mv /etc/${config} /vagrant/etc/guest/${config}
            ln -s /vagrant/etc/guest/${config} /etc/${config}
        fi
    fi
done

# Configs located under ~/*
configs=( .bashrc .composer .profile )
for config in "${configs[@]}"
do
    if [ ! -d /vagrant/etc/guest/${config} ] && [ ! -f /vagrant/etc/guest/${config} ]; then
        if [ -d /home/vagrant/${config} ] || [ -f /home/vagrant/${config} ]; then
            mv /home/vagrant/${config} /vagrant/etc/guest/${config}
            ln -s /vagrant/etc/guest/${config} /home/vagrant/${config}
        fi
    fi
done