#!/usr/bin/env bash

function process_configs () {
    configs_path=$1
    configs=$2
    for config in "${configs[@]}"
    do
        if [ ! -d /vagrant/etc/guest/${config} ] && [ ! -f /vagrant/etc/guest/${config} ]; then
            if [ -d ${configs_path}/${config} ] || [ -f ${configs_path}/${config} ]; then
                sudo rm -rf "${configs_path}/${config}.back"
                sudo cp -rp ${configs_path}/${config} "${configs_path}/${config}.back"
                sudo mv ${configs_path}/${config} /vagrant/etc/guest/${config}
                sudo ln -s /vagrant/etc/guest/${config} ${configs_path}/${config}
            fi
        fi
    done
}

# Enable trace printing and exit on the first error
set -ex

# Make guest configs visible and editable in the host IDE

# Configs located under /etc/*
config_dir="/etc"
# See unlink_configs script
configs=( apache2 php mysql varnish rabbitmq crontab cron.d timezone hosts profile profile.d )
process_configs ${config_dir} ${configs}

# Configs located under ~/*
config_dir="/home/vagrant"
configs=( .bashrc .composer .profile )
process_configs ${config_dir} ${configs}