#!/usr/bin/env bash

vagrant_dir="/vagrant"

source "${vagrant_dir}/scripts/output_functions.sh"

status "Configuring search engine"
incrementNestingLevel

if [[ $1 == "help" ]]; then
    status "Usage: ./m-search-engine mysql/elasticsearch"
    decrementNestingLevel
    exit 0
fi


# Check if user created config.yaml file
if [[ ! -f /vagrant/etc/config.yaml ]]; then
    error "Please make sure you have create a config.yaml file copy from etc/config.yaml.dist"
    decrementNestingLevel
    exit 1
fi

if [[ -z "$(grep "search_engine:" /vagrant/etc/config.yaml)" ]]; then
    sed -i '/environment:/a \ \ search_engine: "mysql"' /vagrant/etc/config.yaml
fi

if [[ $1 == "mysql" ]]; then
    status "Enabling MySQL search engine"
    sed -ie 's/search_engine:.*/search_engine: "mysql"/' /vagrant/etc/config.yaml
elif [[ $1 == "elasticsearch" ]]; then
    status "Enabling ElasticSearch search engine"
    sed -ie 's/search_engine:.*/search_engine: "elasticsearch"/' /vagrant/etc/config.yaml
else
    error "Usage: ./m-search-engine mysql|elasticsearch"
    decrementNestingLevel
    exit 1
fi

bash configure_search_engine

decrementNestingLevel
