#!/usr/bin/env bash

vagrant_dir="/vagrant"

source "${vagrant_dir}/scripts/output_functions.sh"

config_path=$1
config_value=$2

status "Updating Magento config: ${config_path} = ${config_value}"
incrementNestingLevel

magento_context="$(bash "${vagrant_dir}/scripts/guest/get_magento_context")"
magento_instance_db_name="$(bash "${vagrant_dir}/scripts/get_config_value.sh" "magento_context_${magento_context}_db_name")"

mysql -D ${magento_instance_db_name} -e "INSERT INTO core_config_data
    ( scope, scope_id, path, value ) VALUES
    ( 'default', '0', '${config_path}', '${config_value}' )
     ON DUPLICATE KEY UPDATE value = '${config_value}'
;"

decrementNestingLevel
