#!/usr/bin/env bash

vagrant_dir="/vagrant"

source "${vagrant_dir}/scripts/output_functions.sh"

config_path=$1
config_value=$2

status "Updating Magento config: ${config_path} = ${config_value}"
incrementNestingLevel

mysql -D magento -e "INSERT INTO core_config_data
    ( scope, scope_id, path, value ) VALUES
    ( 'default', '0', '${config_path}', '${config_value}' )
     ON DUPLICATE KEY UPDATE value = '${config_value}'
;"

decrementNestingLevel
