#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")/../.." && vagrant_dir=$PWD

source "${vagrant_dir}/scripts/functions.sh"

cd "${vagrant_dir}"

fswatch -0 --exclude="\\.git" --exclude="\\.idea" --exclude=".*___jb_tmp___" --exclude=".*___jb_old___" "${vagrant_dir}" | xargs -0 -n 1 -I {} "/Users/oleksandrpaliarush/Projects/magento2-kubernetes-for-developers/scripts/host/execute_sync" {}

# Explicit exit is necessary to bypass incorrect output from vagrant in case of errors
exit 0
